# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=32, verbose_name='taskName')),
                ('taskDesc', models.CharField(max_length=128, verbose_name='taskDesc')),
                ('taskType', models.IntegerField(choices=[('0', 'OneTime'), ('1', 'Period')], verbose_name='taskType')),
            ],
            options={
                'db_table': 'h_t_task',
            },
        ),
    ]
